version: "3.9"

services:

    um.facultad.fcjs:
        build: .
        ports:
            - 8103:8080
        environment:
            APP_SERVER: 10.147.20.25:3306
            APP_DATABASE: fcjsadm
            APP_USER: root
            APP_PASSWORD: root
            APP_ADD-PROPERTIES: "false"
            APP_LOGGING: "off"
            APP_LIVERELOAD_ENABLED: "true"
            APP_LIVERELOAD_PORT: 35803
            APP_OPEN-IN-VIEW: "false"
