FROM maven:3-eclipse-temurin-21-alpine as build
ENV HOME=/usr/app
RUN mkdir -p $HOME
WORKDIR $HOME
ADD . $HOME
RUN --mount=type=cache,target=/root/.m2 mvn -f $HOME/pom.xml clean package

FROM eclipse-temurin:21-jre-alpine
COPY --from=build /usr/app/target/*.jar app.jar
COPY marca_etec.png marca_etec.png
COPY marca_um.png marca_um.png
ENTRYPOINT ["java","-jar","/app.jar"]
