app:
  port: ${APP_PORT:8080}
  logging: debug
  server: 10.147.20.20:3306
  database: fiadm
  user: root
  password: root
  mail:
    username: envios@um.edu.ar
    password: 4Siby2KPwWIStCyX9gLB

server:
  port: ${app.port}
  
spring:
  datasource:
    url: jdbc:mysql://${app.server}/${app.database}?useSSL=false&serverTimezone=UTC
    username: ${app.user}
    password: ${app.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${app.mail.username}
    password: ${app.mail.password}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

logging:
  level:
    web: ${app.logging}
    org:
      hibernate:
        SQL: ${app.logging}
