sequenceDiagram
    actor U as Usuario
    participant C as Controller REST
    participant UC as Application Service<br/>(Use Case)
    participant AD as JPA Adapter
    participant DB as MySQL Database

    U->>C: POST /inscripcion
    C->>UC: execute(domainModel)
    UC->>AD: save(entity)
    AD->>DB: INSERT
    DB-->>AD: OK
    AD-->>UC: entitySaved
    UC->>UC: generarDocumentos()
    UC->>UC: enviarEmail()
    UC-->>C: domainModelResult
    C-->>U: 201 Created (ResponseDTO)